### ISSUE TITLE
Sign up nor work

### ISSUE THREAD

**Issue by Solankimimoh** [hassanzohdy/advanced-php-mvc-blog#2]
Notice: Undefined variable: loginModel in C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\App\Controllers\Blog\RegisterController.php on line 16

Fatal error: Uncaught Error: Call to a member function isLogged() on null in C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\App\Controllers\Blog\RegisterController.php:16 Stack trace: #0 [internal function]: App\Controllers\Blog\RegisterController->index() #1 C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\vendor\System\Loader.php(51): call_user_func_array(Array, Array) #2 C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\vendor\System\Application.php(71): System\Loader->action('Blog\\Register', 'index', Array) #3 C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\index.php(15): System\Application->run() #4 {main} thrown in C:\xampp\htdocs\darshit\project\advanced-php-mvc-blog-master\advanced-php-mvc-blog-master\App\Controllers\Blog\RegisterController.php on line 16

**Comment by Kwarcek** [comment]
Go to RegisterController.php on line 16
and delete if
It doesn't work (validation if user is login then on login site will be redirected)
